"""add maschinen tables

Revision ID: 507ec2ed41be
Revises: 
Create Date: 2023-03-22 07:15:41.380023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507ec2ed41be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maschinen',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ruestzeit', sa.Float(), nullable=True),
    sa.Column('kostenMinute', sa.Float(), nullable=True),
    sa.Column('ausfallWahrscheinlichkeit', sa.Float(), nullable=True),
    sa.Column('mitarbeiterMin', sa.Integer(), nullable=True),
    sa.Column('mitarbeiterMax', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maschinenbefaehigung',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schrittId', sa.String(), nullable=True),
    sa.Column('taktrate', sa.Float(), nullable=True),
    sa.Column('maschinen_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['maschinen_id'], ['maschinen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maschinenbefaehigung')
    op.drop_table('maschinen')
    # ### end Alembic commands ###
