"""add Produkt related cascades

Revision ID: 87a01f4da4cf
Revises: 0a5b4987f475
Create Date: 2023-03-29 04:29:04.827314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a01f4da4cf'
down_revision = '0a5b4987f475'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('produktbedarf_charge_id_fkey', 'produktbedarf', type_='foreignkey')
    op.drop_constraint('produktbedarf_produkt_id_fkey', 'produktbedarf', type_='foreignkey')
    op.create_foreign_key('produktbedarf_charge_id_fkey', 'produktbedarf', 'charge', ['charge_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('produktbedarf_produkt_id_fkey', 'produktbedarf', 'produkt', ['produkt_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('materialbedarf_produkt_id_fkey', 'materialbedarf', type_='foreignkey')
    op.create_foreign_key('materialbedarf_produkt_id_fkey', 'materialbedarf', 'produkt', ['produkt_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('produktionsschritt_produkt_id_fkey', 'produktionsschritt', type_='foreignkey')
    op.create_foreign_key('produktionsschritt_produkt_id_fkey', 'produktionsschritt', 'produkt', ['produkt_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('produktbedarf_produkt_id_fkey', 'produktbedarf', type_='foreignkey')
    op.drop_constraint('produktbedarf_charge_id_fkey', 'produktbedarf', type_='foreignkey')
    op.create_foreign_key('produktbedarf_produkt_id_fkey', 'produktbedarf', 'produkt', ['produkt_id'], ['id'])
    op.create_foreign_key('produktbedarf_charge_id_fkey', 'produktbedarf', 'charge', ['charge_id'], ['id'])
    op.drop_constraint('produktionsschritt_produkt_id_fkey', 'produktionsschritt', type_='foreignkey')
    op.create_foreign_key('produktionsschritt_produkt_id_fkey', 'produktionsschritt', 'produkt', ['produkt_id'], ['id'])
    op.drop_constraint('materialbedarf_produkt_id_fkey', 'materialbedarf', type_='foreignkey')
    op.create_foreign_key('materialbedarf_produkt_id_fkey', 'materialbedarf', 'produkt', ['produkt_id'], ['id'])
    # ### end Alembic commands ###
