"""add charge and produktbedarf tables

Revision ID: e14b4e7cbc95
Revises: 478f5dc0676e
Create Date: 2023-03-28 05:00:30.169102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e14b4e7cbc95'
down_revision = '478f5dc0676e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('prioritaet', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produktbedarf',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('produkt_id', sa.String(), nullable=False),
    sa.Column('stueckzahl', sa.Integer(), nullable=True),
    sa.Column('charge_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['charge_id'], ['charge.id'], ),
    sa.ForeignKeyConstraint(['produkt_id'], ['produkt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produktbedarf')
    op.drop_table('charge')
    # ### end Alembic commands ###
